import json
d = json.load(open('daily.json', encoding='utf-8'))
news = d.get('news', [])
print("NEWS_TOTAL", len(news))
xh = sum(1 for n in news if ('news.cn' in n.get('url', '')) or ('weibo' in n.get('url', '')))
print("NEWS_REAL_XINHUA_WEIBO", xh)
cn = sum(1 for n in news if 'chinanews' in n.get('url', '') or 'cctv' in n.get('url', ''))
print("NEWS_REAL_OFFICIAL", cn)
topics = d.get('topics', [])
print("TOPICS_TOTAL", len(topics))
print("TOPICS_WITH_REAL", sum(1 for t in topics if t.get('real_url')))
print("REPOSTS_WITH_REAL", sum(1 for t in d.get('reposts', []) if t.get('real_url')))
print("AIP_REAL_FLAG", d.get('aiproduct_real'))
print("DATE", d.get('date'), "GEN", d.get('gen'))
